services:
  app:
    # container_name: name
    # image: name
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules/
    ports:
      # - "5173:3000"
      - "3000:3000"
    expose:
      # - "5173"
      - "3000"